Acme\Bundle\CustomBundle\Model\ProductPatternAction:
    constraints:
        - PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraint\PropertyAction: ~
    properties:
        field:
           - Type:
                type: string
           - NotBlank: ~
           - Length:
               max: 255
           - PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraint\ExistingSetField: ~
        attributes:
            - Type:
                type: array
            - NotBlank:
                message: The key "attributes" is missing or empty.
            - Acme\Bundle\CustomBundle\Validator\Constraints\ExistingAttributes: ~
        pattern:
           - Type:
                type: string
           - NotBlank: ~
           - Length:
               max: 255