services:
    acme.action_applier.pattern:
        class: Acme\Bundle\CustomBundle\ActionApplier\PatternActionApplier
        arguments:
            - '@pim_catalog.updater.product_property_setter'
        tags:
            - { name: akeneo_rule_engine.action_applier, priority: 100 }

    acme.denormalizer.product_rule.pattern_action:
        class: Acme\Bundle\CustomBundle\Denormalizer\ProductRule\PatternActionDenormalizer
        tags:
            - { name: 'pimee_catalog_rule.denormalizer.product_rule' }

    acme.validator.existing_attributes:
        class: Acme\Bundle\CustomBundle\Validator\Constraints\ExistingAttributesValidator
        arguments:
            - '@pim_catalog.repository.attribute'
        tags:
            - { name: validator.constraint_validator, alias: pimee_constraint_attributes_validator }
